version: '3'
services:

  my-web:
    image: my-web
    links:
      - my-app
    depends_on:
      - my-app
    ports:
      - 80:80

  my-app:
    image: my-app
    links:
      - my-db
    depends_on:
      - my-db

  my-db:
    image: my-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_db
