version: '3'
services:

  my-web:
    image: node:9.3.0-alpine
    links:
      - my-app
    depends_on:
      - my-app
    ports:
      - 8081:8081
    working_dir: /opt/my-web
    volumes:
      - ./my-web:/opt/my-web
    command: npm run dev
    environment:
      HOST: 0.0.0.0
      PORT: 8081

  my-app:
    image: java:8-jdk-alpine
    links:
      - my-db
    depends_on:
      - my-db
    ports:
      - 8080:8080
      - 5005:5005
    working_dir: /opt/my-app
    volumes:
      - ./my-app:/opt/my-app
      - $HOME/.m2:/root/.m2
    command: ./mvnw spring-boot:run -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"

  my-db:
    build: ./my-db
    image: my-db
    ports:
      - 3306:3306
    volumes:
      - ./my-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_db
