version: '3'
services:

  my-web:
    image: my-web
    links:
      - my-app
    depends_on:
      - my-app
    ports:
      - 80:80

  my-app:
    image: my-app
    links:
      - my-db
    depends_on:
      - my-db
    ports:
      - 8080:8080

  my-db:
    image: my-db
    ports:
      - 3306:3306
    volumes:
      - ./my-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_db
